on:
  push:

jobs:
  onedeploy:
    runs-on: ubuntu-latest
    name: Deploy static site from scratch
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Check out IaC Cloudformation
        uses: actions/checkout@master
        with:
          repository: kaihendry/s3-cloudfront-cloudformation
      - run: find "$(pwd)"
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: hola
          template: template.yml
          parameter-overrides: "DomainName=hola.natalian.org,AcmWildcard=arn:aws:acm:us-east-1:407461997746:certificate/8e3ee384-d4f3-47b7-b0a6-c28fa0b4a26b"
          no-fail-on-empty-changeset: "1"
      - name: Checkout project files
        uses: actions/checkout@v2
      - run: find "$(pwd)"
      - name: S3 Sync to deploy
        run: aws s3 sync --acl public-read index.html s3://hola.natalian.org
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "$(aws cloudfront list-distributions --query "DistributionList.Items[*].{Alias:Aliases.Items[0],Id:Id}[?Alias=='hola.natalian.org'].Id" --output text)" \
            --paths '/*'
